// Reverse-engineered schema of the private AnkiWeb study API, decoded from the
// study page's JS bundle on 2026-09-02. Field numbers matter; names are ours.
// Regenerate with: go generate ./internal/ankiweb/...

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: ankiweb.proto

package ankiwebpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginStatus int32

const (
	LoginStatus_LOGIN_UNKNOWN       LoginStatus = 0
	LoginStatus_LOGIN_AUTHENTICATED LoginStatus = 1
	LoginStatus_LOGIN_INVALID_USER  LoginStatus = 2
	LoginStatus_LOGIN_INVALID_PASS  LoginStatus = 3
)

// Enum value maps for LoginStatus.
var (
	LoginStatus_name = map[int32]string{
		0: "LOGIN_UNKNOWN",
		1: "LOGIN_AUTHENTICATED",
		2: "LOGIN_INVALID_USER",
		3: "LOGIN_INVALID_PASS",
	}
	LoginStatus_value = map[string]int32{
		"LOGIN_UNKNOWN":       0,
		"LOGIN_AUTHENTICATED": 1,
		"LOGIN_INVALID_USER":  2,
		"LOGIN_INVALID_PASS":  3,
	}
)

func (x LoginStatus) Enum() *LoginStatus {
	p := new(LoginStatus)
	*p = x
	return p
}

func (x LoginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ankiweb_proto_enumTypes[0].Descriptor()
}

func (LoginStatus) Type() protoreflect.EnumType {
	return &file_ankiweb_proto_enumTypes[0]
}

func (x LoginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginStatus.Descriptor instead.
func (LoginStatus) EnumDescriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{0}
}

// POST https://ankiweb.net/svc/account/login
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_ankiweb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        LoginStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=ankiweb.LoginStatus" json:"status,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_ankiweb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetStatus() LoginStatus {
	if x != nil {
		return x.Status
	}
	return LoginStatus_LOGIN_UNKNOWN
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// POST https://ankiweb.net/svc/decks/deck-list-info
type DeckListRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MinutesWestOfUtc *int32                 `protobuf:"varint,1,opt,name=minutes_west_of_utc,json=minutesWestOfUtc,proto3,oneof" json:"minutes_west_of_utc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeckListRequest) Reset() {
	*x = DeckListRequest{}
	mi := &file_ankiweb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckListRequest) ProtoMessage() {}

func (x *DeckListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckListRequest.ProtoReflect.Descriptor instead.
func (*DeckListRequest) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{2}
}

func (x *DeckListRequest) GetMinutesWestOfUtc() int32 {
	if x != nil && x.MinutesWestOfUtc != nil {
		return *x.MinutesWestOfUtc
	}
	return 0
}

type DeckListResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TopNode             *DeckNode              `protobuf:"bytes,1,opt,name=top_node,json=topNode,proto3" json:"top_node,omitempty"`
	CurrentDeckId       int64                  `protobuf:"varint,2,opt,name=current_deck_id,json=currentDeckId,proto3" json:"current_deck_id,omitempty"`
	CollectionSizeBytes uint32                 `protobuf:"varint,3,opt,name=collection_size_bytes,json=collectionSizeBytes,proto3" json:"collection_size_bytes,omitempty"`
	MediaSizeBytes      uint64                 `protobuf:"varint,4,opt,name=media_size_bytes,json=mediaSizeBytes,proto3" json:"media_size_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeckListResponse) Reset() {
	*x = DeckListResponse{}
	mi := &file_ankiweb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckListResponse) ProtoMessage() {}

func (x *DeckListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckListResponse.ProtoReflect.Descriptor instead.
func (*DeckListResponse) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{3}
}

func (x *DeckListResponse) GetTopNode() *DeckNode {
	if x != nil {
		return x.TopNode
	}
	return nil
}

func (x *DeckListResponse) GetCurrentDeckId() int64 {
	if x != nil {
		return x.CurrentDeckId
	}
	return 0
}

func (x *DeckListResponse) GetCollectionSizeBytes() uint32 {
	if x != nil {
		return x.CollectionSizeBytes
	}
	return 0
}

func (x *DeckListResponse) GetMediaSizeBytes() uint64 {
	if x != nil {
		return x.MediaSizeBytes
	}
	return 0
}

type DeckNode struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DeckId                 int64                  `protobuf:"varint,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Children               []*DeckNode            `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Level                  uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Collapsed              bool                   `protobuf:"varint,5,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	ReviewCount            uint32                 `protobuf:"varint,6,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	LearnCount             uint32                 `protobuf:"varint,7,opt,name=learn_count,json=learnCount,proto3" json:"learn_count,omitempty"`
	NewCount               uint32                 `protobuf:"varint,8,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	TotalInDeck            uint32                 `protobuf:"varint,13,opt,name=total_in_deck,json=totalInDeck,proto3" json:"total_in_deck,omitempty"`
	TotalIncludingChildren uint32                 `protobuf:"varint,14,opt,name=total_including_children,json=totalIncludingChildren,proto3" json:"total_including_children,omitempty"`
	Filtered               bool                   `protobuf:"varint,16,opt,name=filtered,proto3" json:"filtered,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeckNode) Reset() {
	*x = DeckNode{}
	mi := &file_ankiweb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckNode) ProtoMessage() {}

func (x *DeckNode) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckNode.ProtoReflect.Descriptor instead.
func (*DeckNode) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{4}
}

func (x *DeckNode) GetDeckId() int64 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

func (x *DeckNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeckNode) GetChildren() []*DeckNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *DeckNode) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DeckNode) GetCollapsed() bool {
	if x != nil {
		return x.Collapsed
	}
	return false
}

func (x *DeckNode) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *DeckNode) GetLearnCount() uint32 {
	if x != nil {
		return x.LearnCount
	}
	return 0
}

func (x *DeckNode) GetNewCount() uint32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

func (x *DeckNode) GetTotalInDeck() uint32 {
	if x != nil {
		return x.TotalInDeck
	}
	return 0
}

func (x *DeckNode) GetTotalIncludingChildren() uint32 {
	if x != nil {
		return x.TotalIncludingChildren
	}
	return 0
}

func (x *DeckNode) GetFiltered() bool {
	if x != nil {
		return x.Filtered
	}
	return false
}

// POST https://ankiweb.net/svc/decks/select-deck
type SelectDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        int64                  `protobuf:"varint,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectDeckRequest) Reset() {
	*x = SelectDeckRequest{}
	mi := &file_ankiweb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDeckRequest) ProtoMessage() {}

func (x *SelectDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDeckRequest.ProtoReflect.Descriptor instead.
func (*SelectDeckRequest) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{5}
}

func (x *SelectDeckRequest) GetDeckId() int64 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

type SelectDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectDeckResponse) Reset() {
	*x = SelectDeckResponse{}
	mi := &file_ankiweb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDeckResponse) ProtoMessage() {}

func (x *SelectDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDeckResponse.ProtoReflect.Descriptor instead.
func (*SelectDeckResponse) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{6}
}

// POST https://ankiuser.net/svc/study/study-cards
// An empty request returns the next cards. With `answer` set it grades that card
// first. `next_card_id` tells the server which card the client is about to show.
type StudyCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *CardAnswer            `protobuf:"bytes,1,opt,name=answer,proto3,oneof" json:"answer,omitempty"`
	NextCardId    *int64                 `protobuf:"varint,2,opt,name=next_card_id,json=nextCardId,proto3,oneof" json:"next_card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyCardsRequest) Reset() {
	*x = StudyCardsRequest{}
	mi := &file_ankiweb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyCardsRequest) ProtoMessage() {}

func (x *StudyCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyCardsRequest.ProtoReflect.Descriptor instead.
func (*StudyCardsRequest) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{7}
}

func (x *StudyCardsRequest) GetAnswer() *CardAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *StudyCardsRequest) GetNextCardId() int64 {
	if x != nil && x.NextCardId != nil {
		return *x.NextCardId
	}
	return 0
}

type StudyCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchedVer      uint32                 `protobuf:"varint,1,opt,name=sched_ver,json=schedVer,proto3" json:"sched_ver,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	NewCount      uint32                 `protobuf:"varint,3,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	LearnCount    uint32                 `protobuf:"varint,4,opt,name=learn_count,json=learnCount,proto3" json:"learn_count,omitempty"`
	ReviewCount   uint32                 `protobuf:"varint,5,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyCardsResponse) Reset() {
	*x = StudyCardsResponse{}
	mi := &file_ankiweb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyCardsResponse) ProtoMessage() {}

func (x *StudyCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyCardsResponse.ProtoReflect.Descriptor instead.
func (*StudyCardsResponse) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{8}
}

func (x *StudyCardsResponse) GetSchedVer() uint32 {
	if x != nil {
		return x.SchedVer
	}
	return 0
}

func (x *StudyCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *StudyCardsResponse) GetNewCount() uint32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

func (x *StudyCardsResponse) GetLearnCount() uint32 {
	if x != nil {
		return x.LearnCount
	}
	return 0
}

func (x *StudyCardsResponse) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`                        // rendered HTML
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`                            // rendered HTML (includes the question above <hr id=answer>)
	CountIndex    uint32                 `protobuf:"varint,4,opt,name=count_index,json=countIndex,proto3" json:"count_index,omitempty"` // 0 new, 1 learn, 2 review
	ButtonLabels  []string               `protobuf:"bytes,5,rep,name=button_labels,json=buttonLabels,proto3" json:"button_labels,omitempty"`
	NoteId        int64                  `protobuf:"varint,6,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	TemplateIndex uint32                 `protobuf:"varint,7,opt,name=template_index,json=templateIndex,proto3" json:"template_index,omitempty"`
	NextStates    *NextStates            `protobuf:"bytes,8,opt,name=next_states,json=nextStates,proto3" json:"next_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_ankiweb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{9}
}

func (x *Card) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *Card) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Card) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Card) GetCountIndex() uint32 {
	if x != nil {
		return x.CountIndex
	}
	return 0
}

func (x *Card) GetButtonLabels() []string {
	if x != nil {
		return x.ButtonLabels
	}
	return nil
}

func (x *Card) GetNoteId() int64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *Card) GetTemplateIndex() uint32 {
	if x != nil {
		return x.TemplateIndex
	}
	return 0
}

func (x *Card) GetNextStates() *NextStates {
	if x != nil {
		return x.NextStates
	}
	return nil
}

// SchedulingState messages are opaque to us: we only echo them back, so they
// are declared as bytes. A length-delimited field read as bytes is the exact
// wire encoding of the submessage.
type NextStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       []byte                 `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	Again         []byte                 `protobuf:"bytes,2,opt,name=again,proto3" json:"again,omitempty"`
	Hard          []byte                 `protobuf:"bytes,3,opt,name=hard,proto3" json:"hard,omitempty"`
	Good          []byte                 `protobuf:"bytes,4,opt,name=good,proto3" json:"good,omitempty"`
	Easy          []byte                 `protobuf:"bytes,5,opt,name=easy,proto3" json:"easy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextStates) Reset() {
	*x = NextStates{}
	mi := &file_ankiweb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextStates) ProtoMessage() {}

func (x *NextStates) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextStates.ProtoReflect.Descriptor instead.
func (*NextStates) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{10}
}

func (x *NextStates) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *NextStates) GetAgain() []byte {
	if x != nil {
		return x.Again
	}
	return nil
}

func (x *NextStates) GetHard() []byte {
	if x != nil {
		return x.Hard
	}
	return nil
}

func (x *NextStates) GetGood() []byte {
	if x != nil {
		return x.Good
	}
	return nil
}

func (x *NextStates) GetEasy() []byte {
	if x != nil {
		return x.Easy
	}
	return nil
}

type CardAnswer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CardId           int64                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AnswerButton     uint32                 `protobuf:"varint,2,opt,name=answer_button,json=answerButton,proto3" json:"answer_button,omitempty"` // 1 Again, 2 Hard, 3 Good, 4 Easy
	TimeTakenMillis  uint32                 `protobuf:"varint,3,opt,name=time_taken_millis,json=timeTakenMillis,proto3" json:"time_taken_millis,omitempty"`
	AnsweredAtMillis int64                  `protobuf:"varint,4,opt,name=answered_at_millis,json=answeredAtMillis,proto3" json:"answered_at_millis,omitempty"`
	CurrentState     []byte                 `protobuf:"bytes,5,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	NextState        []byte                 `protobuf:"bytes,6,opt,name=next_state,json=nextState,proto3" json:"next_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardAnswer) Reset() {
	*x = CardAnswer{}
	mi := &file_ankiweb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAnswer) ProtoMessage() {}

func (x *CardAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_ankiweb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAnswer.ProtoReflect.Descriptor instead.
func (*CardAnswer) Descriptor() ([]byte, []int) {
	return file_ankiweb_proto_rawDescGZIP(), []int{11}
}

func (x *CardAnswer) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *CardAnswer) GetAnswerButton() uint32 {
	if x != nil {
		return x.AnswerButton
	}
	return 0
}

func (x *CardAnswer) GetTimeTakenMillis() uint32 {
	if x != nil {
		return x.TimeTakenMillis
	}
	return 0
}

func (x *CardAnswer) GetAnsweredAtMillis() int64 {
	if x != nil {
		return x.AnsweredAtMillis
	}
	return 0
}

func (x *CardAnswer) GetCurrentState() []byte {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *CardAnswer) GetNextState() []byte {
	if x != nil {
		return x.NextState
	}
	return nil
}

var File_ankiweb_proto protoreflect.FileDescriptor

const file_ankiweb_proto_rawDesc = "" +
	"\n" +
	"\rankiweb.proto\x12\aankiweb\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"S\n" +
	"\rLoginResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.ankiweb.LoginStatusR\x06status\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"]\n" +
	"\x0fDeckListRequest\x122\n" +
	"\x13minutes_west_of_utc\x18\x01 \x01(\x05H\x00R\x10minutesWestOfUtc\x88\x01\x01B\x16\n" +
	"\x14_minutes_west_of_utc\"\xc6\x01\n" +
	"\x10DeckListResponse\x12,\n" +
	"\btop_node\x18\x01 \x01(\v2\x11.ankiweb.DeckNodeR\atopNode\x12&\n" +
	"\x0fcurrent_deck_id\x18\x02 \x01(\x03R\rcurrentDeckId\x122\n" +
	"\x15collection_size_bytes\x18\x03 \x01(\rR\x13collectionSizeBytes\x12(\n" +
	"\x10media_size_bytes\x18\x04 \x01(\x04R\x0emediaSizeBytes\"\xf5\x02\n" +
	"\bDeckNode\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\x03R\x06deckId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\bchildren\x18\x03 \x03(\v2\x11.ankiweb.DeckNodeR\bchildren\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\x1c\n" +
	"\tcollapsed\x18\x05 \x01(\bR\tcollapsed\x12!\n" +
	"\freview_count\x18\x06 \x01(\rR\vreviewCount\x12\x1f\n" +
	"\vlearn_count\x18\a \x01(\rR\n" +
	"learnCount\x12\x1b\n" +
	"\tnew_count\x18\b \x01(\rR\bnewCount\x12\"\n" +
	"\rtotal_in_deck\x18\r \x01(\rR\vtotalInDeck\x128\n" +
	"\x18total_including_children\x18\x0e \x01(\rR\x16totalIncludingChildren\x12\x1a\n" +
	"\bfiltered\x18\x10 \x01(\bR\bfiltered\",\n" +
	"\x11SelectDeckRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\x03R\x06deckId\"\x14\n" +
	"\x12SelectDeckResponse\"\x88\x01\n" +
	"\x11StudyCardsRequest\x120\n" +
	"\x06answer\x18\x01 \x01(\v2\x13.ankiweb.CardAnswerH\x00R\x06answer\x88\x01\x01\x12%\n" +
	"\fnext_card_id\x18\x02 \x01(\x03H\x01R\n" +
	"nextCardId\x88\x01\x01B\t\n" +
	"\a_answerB\x0f\n" +
	"\r_next_card_id\"\xb7\x01\n" +
	"\x12StudyCardsResponse\x12\x1b\n" +
	"\tsched_ver\x18\x01 \x01(\rR\bschedVer\x12#\n" +
	"\x05cards\x18\x02 \x03(\v2\r.ankiweb.CardR\x05cards\x12\x1b\n" +
	"\tnew_count\x18\x03 \x01(\rR\bnewCount\x12\x1f\n" +
	"\vlearn_count\x18\x04 \x01(\rR\n" +
	"learnCount\x12!\n" +
	"\freview_count\x18\x05 \x01(\rR\vreviewCount\"\x8f\x02\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x1f\n" +
	"\vcount_index\x18\x04 \x01(\rR\n" +
	"countIndex\x12#\n" +
	"\rbutton_labels\x18\x05 \x03(\tR\fbuttonLabels\x12\x17\n" +
	"\anote_id\x18\x06 \x01(\x03R\x06noteId\x12%\n" +
	"\x0etemplate_index\x18\a \x01(\rR\rtemplateIndex\x124\n" +
	"\vnext_states\x18\b \x01(\v2\x13.ankiweb.NextStatesR\n" +
	"nextStates\"x\n" +
	"\n" +
	"NextStates\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\fR\acurrent\x12\x14\n" +
	"\x05again\x18\x02 \x01(\fR\x05again\x12\x12\n" +
	"\x04hard\x18\x03 \x01(\fR\x04hard\x12\x12\n" +
	"\x04good\x18\x04 \x01(\fR\x04good\x12\x12\n" +
	"\x04easy\x18\x05 \x01(\fR\x04easy\"\xe8\x01\n" +
	"\n" +
	"CardAnswer\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x03R\x06cardId\x12#\n" +
	"\ranswer_button\x18\x02 \x01(\rR\fanswerButton\x12*\n" +
	"\x11time_taken_millis\x18\x03 \x01(\rR\x0ftimeTakenMillis\x12,\n" +
	"\x12answered_at_millis\x18\x04 \x01(\x03R\x10answeredAtMillis\x12#\n" +
	"\rcurrent_state\x18\x05 \x01(\fR\fcurrentState\x12\x1d\n" +
	"\n" +
	"next_state\x18\x06 \x01(\fR\tnextState*i\n" +
	"\vLoginStatus\x12\x11\n" +
	"\rLOGIN_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13LOGIN_AUTHENTICATED\x10\x01\x12\x16\n" +
	"\x12LOGIN_INVALID_USER\x10\x02\x12\x16\n" +
	"\x12LOGIN_INVALID_PASS\x10\x03B:Z8github.com/amarcozzi/anki-mcp/internal/ankiweb/ankiwebpbb\x06proto3"

var (
	file_ankiweb_proto_rawDescOnce sync.Once
	file_ankiweb_proto_rawDescData []byte
)

func file_ankiweb_proto_rawDescGZIP() []byte {
	file_ankiweb_proto_rawDescOnce.Do(func() {
		file_ankiweb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ankiweb_proto_rawDesc), len(file_ankiweb_proto_rawDesc)))
	})
	return file_ankiweb_proto_rawDescData
}

var file_ankiweb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ankiweb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ankiweb_proto_goTypes = []any{
	(LoginStatus)(0),           // 0: ankiweb.LoginStatus
	(*LoginRequest)(nil),       // 1: ankiweb.LoginRequest
	(*LoginResponse)(nil),      // 2: ankiweb.LoginResponse
	(*DeckListRequest)(nil),    // 3: ankiweb.DeckListRequest
	(*DeckListResponse)(nil),   // 4: ankiweb.DeckListResponse
	(*DeckNode)(nil),           // 5: ankiweb.DeckNode
	(*SelectDeckRequest)(nil),  // 6: ankiweb.SelectDeckRequest
	(*SelectDeckResponse)(nil), // 7: ankiweb.SelectDeckResponse
	(*StudyCardsRequest)(nil),  // 8: ankiweb.StudyCardsRequest
	(*StudyCardsResponse)(nil), // 9: ankiweb.StudyCardsResponse
	(*Card)(nil),               // 10: ankiweb.Card
	(*NextStates)(nil),         // 11: ankiweb.NextStates
	(*CardAnswer)(nil),         // 12: ankiweb.CardAnswer
}
var file_ankiweb_proto_depIdxs = []int32{
	0,  // 0: ankiweb.LoginResponse.status:type_name -> ankiweb.LoginStatus
	5,  // 1: ankiweb.DeckListResponse.top_node:type_name -> ankiweb.DeckNode
	5,  // 2: ankiweb.DeckNode.children:type_name -> ankiweb.DeckNode
	12, // 3: ankiweb.StudyCardsRequest.answer:type_name -> ankiweb.CardAnswer
	10, // 4: ankiweb.StudyCardsResponse.cards:type_name -> ankiweb.Card
	11, // 5: ankiweb.Card.next_states:type_name -> ankiweb.NextStates
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ankiweb_proto_init() }
func file_ankiweb_proto_init() {
	if File_ankiweb_proto != nil {
		return
	}
	file_ankiweb_proto_msgTypes[2].OneofWrappers = []any{}
	file_ankiweb_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ankiweb_proto_rawDesc), len(file_ankiweb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ankiweb_proto_goTypes,
		DependencyIndexes: file_ankiweb_proto_depIdxs,
		EnumInfos:         file_ankiweb_proto_enumTypes,
		MessageInfos:      file_ankiweb_proto_msgTypes,
	}.Build()
	File_ankiweb_proto = out.File
	file_ankiweb_proto_goTypes = nil
	file_ankiweb_proto_depIdxs = nil
}
